(defattrs :enum {:fill "#a0ffa0"})
(defattrs :bool {:fill "#ffb0a0"})
(defattrs :uint {:fill "#a0fafa"})
(defattrs :fixed {:fill "#ffffa0"})
(defattrs :varint {:fill "#e4b5f7"})

(def vlqcolor (fn [label span color]
	(draw-box (fn [left top width height]
		(append-svg (text label {
			:x (/ (+ left left width) 2.0)
			:y (+ top 1 (/ height 2.0))
			:text-anchor "middle"
			:dominant-baseline "middle"
			:font-size 16
			:font-family "sans-serif"
		}))
		(draw-line (- (+ left width) 5) top (- (+ left width) 15) (+ top height) :border-related)
		(draw-line (- (+ left width) 10) top (- (+ left width) 20) (+ top height) :border-related)
	) [{:span span} color])
))

(def vlq (fn [label span]
	(vlqcolor label span :varint)
))

(def column-labels ["0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "10" "11" "12" "13" "14" "15"])

(draw-column-headers)
(draw-box "version" [{:span 3} :enum])
(draw-box "serving_size" [{:span 3} :enum])
(draw-box "type" [{:span 2} :enum])
(draw-box "glass" [{:span 5} :enum])
(draw-box "sub" [{:span 1} :bool])
(draw-box "size_units" [{:span 2} :enum])
(draw-box (text "small" {:font-size 14}) :bool)
(draw-box "bjcp_style" [{:span 7} :uint])
(vlq "name_len" 8)
(draw-gap "name")
(vlq "description_len" 8)
(draw-gap "description")
(draw-bottom)
(draw-box "if small, then:" {:span 16 :borders #{}})
(next-row)
(draw-column-headers)
(draw-box "batch" [{:span 5} :uint])
(draw-box "boil_diff" [{:span 3} :uint])
(draw-box "" {:span 8 :borders #{}})
(draw-box "else:" {:span 16 :borders #{}})
(next-row)
(draw-column-headers)
(vlq "large_batch" 8)
(vlq "large_boil_diff" 8)
(draw-box "end if" {:span 16 :borders #{}})
(next-row)
(draw-box "if serving_size == 0b111" {:span 16 :borders #{}})
(next-row)
(draw-column-headers)
(vlq "custom_serving_size" 8)
(next-row)
(draw-box "end if" {:span 16 :borders #{}})
(next-row)
(draw-column-headers)
(draw-box "fermentable_len" [{:span 4} :uint])
(draw-box "misc_len" [{:span 4} :uint])
(draw-box "hops_len" [{:span 5} :uint])
(draw-box "yeast_len" [{:span 3} :uint])
(draw-gap "fermentables")
(draw-gap "hops")
(draw-gap "misc")
(draw-gap "yeast")
(draw-bottom)
(draw-box "if type != extract, then:" {:span 16 :borders #{}})
(next-row)
(draw-column-headers)
(draw-box "wtr" [{:span 1} :bool])
(draw-box "mash_step_len" [{:span 7} :uint])
(draw-gap "mash_steps")
(draw-bottom)
(draw-box "if wtr" {:span 16 :borders #{}})
(next-row)
(draw-column-headers)
(vlq "ca" 8)
(vlq "mg" 8)
(vlq "na" 8)
(vlq "cl" 8)
(vlq "so4" 8)
(vlq "hco3" 8)
(draw-box "end if" {:span 16 :borders #{}})
(next-row)
(draw-box "end if" {:span 16 :borders #{}})
(next-row)
(draw-box "if co2 != 2.4 or has_fermentation_steps" {:span 16 :borders #{}})
(next-row)
(draw-column-headers)
(vlqcolor "co2.1" 5 :fixed)
(draw-box "ferm_len" [{:span 3} :uint])
(draw-gap "fermentation_steps")
(draw-bottom)
